services:
  glassfish:
    build: .
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=desafiotec
      - DB_USER=postgres
      - DB_PASSWORD=password

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=desafiotec
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: